Add copy button to text
algovengers/MindMate pull request #123
Opened 2024-05-22 12:58 UTC by panam1916

Issue #110 

Add Feature of Copy Text option

2024-05-23 12:35 UTC, afeefuddin requested changes

2024-05-23 12:35 UTC, afeefuddin commented on Frontend/src/pages/message/message.js
> +      let wss = new WebSocket(`ws://mindmate-ws.onrender.com?id=${chatId}`);
Why have you changed this?

2024-05-23 12:35 UTC, afeefuddin commented on Frontend/src/pages/message/Chat.js
> +import { LuCopy } from 'react-icons/lu'; // Assuming LuCopy is an icon for copy
No need to add a comment here

2024-05-23 14:23 UTC, panam1916 commented on Frontend/src/pages/message/message.js
> +      let wss = new WebSocket(`ws://mindmate-ws.onrender.com?id=${chatId}`);
oh sorry i just change and push it again

2024-05-23 14:29 UTC, panam1916 commented
Hey just check is it alright?

2024-05-29 11:04 UTC, afeefuddin commented
Squash both the commits

2024-05-29 15:01 UTC, panam1916 commented
> Squash both the commits

Hey , I squash both commits Please Check it


 ([detached HEAD 2aa3343] Add copy button to text and other changes
 Date: Wed May 22 18:24:54 2024 +0530
 3 files changed, 54 insertions(+), 9 deletions(-)
 create mode 100644 Frontend/src/pages/message/Chat.js
Successfully rebased and updated refs/heads/copy.)

2024-05-29 16:42 UTC, afeefuddin commented
@panam1916 Now I see 4 commits, Read about squashing [here](https://stackoverflow.com/questions/35703556/what-does-it-mean-to-squash-commits-in-git)

2024-05-29 16:49 UTC, panam1916 commented
> @panam1916 Now I see 4 commits, Read about squashing [here](https://stackoverflow.com/questions/35703556/what-does-it-mean-to-squash-commits-in-git)

so i remove commits which are not squash?

2024-05-29 19:00 UTC, panam1916 commented
Do I need to update my branch?

2024-06-01 10:26 UTC, panam1916 commented
> @panam1916 Now I see 4 commits, Read about squashing [here](https://stackoverflow.com/questions/35703556/what-does-it-mean-to-squash-commits-in-git)

Hi Can you Check and tell me whether there is any mistake or not

2024-06-01 12:58 UTC, panam1916 commented
Hey there happen lot of confusion please guide me what i do

2024-06-01 13:11 UTC, panam1916 commented
> @panam1916 Now I see 4 commits, Read about squashing [here](https://stackoverflow.com/questions/35703556/what-does-it-mean-to-squash-commits-in-git)

Hey I created New pr #139 Can you check that in this already lot of messup

2024-06-02 08:47 UTC, closed without merging